Add duplicate posting reply
filamentphp/discord-bot pull request #5
Opened 2022-10-04 06:06 UTC by saade

`➿` its `:loop:` emoji.

2022-10-04 09:37 UTC, zepfietje commented
Other emoji suggestion: 🔁.

2022-10-06 12:05 UTC, saade commented
oops sorry

2022-10-13 07:26 UTC, zepfietje requested changes

2022-10-13 07:26 UTC, zepfietje commented on index.js
> +        '➿': `Please do not post the same question across different channels.`,
```suggestion
        '🔀': `Please don't send the same message in different channels.`,
```

2022-10-13 07:28 UTC, zepfietje requested changes

2022-10-13 07:28 UTC, zepfietje commented on index.js
> +        '🔀': `Please don't send the same message in different channels.`,
```suggestion
        '🔀': `Please don't post the same message across different channels.`,
```

2022-10-13 07:28 UTC, merged